export const TOGGLE_EDIT_DREAM_TEXT = 'TOGGLE_EDIT_DREAM_TEXT'
export const UPDATE_DREAM_TEXT = 'UPDATE_DREAM_TEXT'
export const SAVE_DREAM = 'SAVE_DREAM'
export const CANCEL_CREATE_DREAM = 'CANCEL_CREATE_DREAM'
